// src/Components/Footer.tsx
import React from "react";

import { Box, Flex, Link, Text } from "@chakra-ui/react";

const Footer = () => {
  return (
    <Box as="footer" background="#FFFC31" color="#1C2826" fontFamily="FiraCode, sans, serif" mt="90px">
      <Flex
        fontWeight="bolder"
        justifyContent={["left", "space-around"]}
        alignItems={["center"]}
        padding={["10px", "0"]}
        height={["auto", "60px"]}
        textTransform="uppercase"
        flexDirection={["column", "row"]}
      >
        <Flex alignItems="center" p={["10px", "0"]}>
          <Link
            href="https://github.com/Jorgen-Jr/calculadora_de_dutos"
            alt="Link para perfil do github - 'Feito com amor por Jorge.'"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              textDecoration: "none",
            }}
          >
            <Box className="github-link">
              <Text as="span" style={{ width: "15px" }}>
                {" "}
              </Text>{" "}
              <Text as="span">
                Made with{" "}
                <Text as="span" role="img" aria-label="heart emoji" color="red">
                  ❤️
                </Text>{" "}
                by Jorge © {new Date().getFullYear()}
              </Text>
            </Box>
          </Link>
        </Flex>
      </Flex>
    </Box>
  );
};

export default Footer;

// src/components/footer.svelte
<main>
	<div class="footer-container footer-background">
		<a
			href="https://github.com/Jorgen-Jr/calculadora_de_dutos"
			target="_blank"
			rel="noopener noreferrer"
			class="github-link"
		>
			<span
				>Made with <span class="heart-emoji" role="img" aria-label="heart emoji">❤️</span> by Jorge</span
			>
		</a>
	</div>
</main>

<style>
	.footer-container {
		position: fixed;
		bottom: 0;
		width: 100%;
	}
	.footer-background {
		background-color: #6366f1;
		padding: 15px;
		text-align: center;
	}
	.github-link {
		display: flex;
		color: rgb(238, 238, 255);
		justify-content: center;
		text-decoration: none;
		transition: 0.2s;
	}
	.github-link:hover {
		color: white;
	}
	.heart-emoji {
		color: red;
	}
</style>
